### ISSUE TITLE
Mediator pattern for communication between components

### ISSUE THREAD

**Issue by pkraker** [OpenKnowledgeMaps/Headstart#10]
Currently, the components of the visualization communicate directly with each other. When an event is triggered that effects two or more components (e.g. a zoom which updates both the chart and filters the list elements to show only papers of the zoomed area), the component which was notified about the event (in this case the chart), also directly updates the other components (in this case the list).

Therefore, there is high dependency between the different components and interaction is distributed and hard to manage. In the mediator pattern, components do not directly communicate with each other but through a mediator object. This would result in more loosely coupled components, and most possibly a better overview of the interaction between the components.

**Comment by Bubblbu** [comment]
Basic mediator structure has been implemented with d3d4267e46d2a631b5c7258595b0d58c7d510a70. All interactions are routed through the mediator which at the moment then just calls the respective methods in the FSMs. No new logic has been introduced in the mediator.

Some open issues:

+ *recordAction* - d3d4267e46d2a631b5c7258595b0d58c7d510a70:
A new channel has been introduced for `recordAction()`, but instead the call `headstart.recordAction()` could simply be moved into the mediator.

+ Features that have been moved into the mediator, but could not be tested yet, because current test data/config is not using those:
    + *mouseover* and *mouseout* for preview images -  0976a579ee301e09ccb4615c7a3590ba25c419d1
    + *bookmarking* - fd45133a84c59fb9798fa458e4bda43bec752072

**Comment by pkraker** [comment]
@Bubblbu Please open new issues for the above mentioned problems and reference them here.

**Comment by pkraker** [comment]
We should complete the implementation asap. See: https://github.com/pkraker/Headstart/issues/41
