### ISSUE TITLE
issue with maps rotation results in awkward layout of bubbles

### ISSUE THREAD

**Issue by chreman** [OpenKnowledgeMaps/Headstart#336]
Especially in BASE-searches, bubbles that contain papers that can be considered topical "outliers" are placed far outside the rest of the map. This gives them a higher visual emphasis in comparison the the "main content" of the map, which also becomes harder to navigate.

Example: map of sugar from 1665-01-01 to 2019-02-12  Document types: Journal/newspaper article

**Comment by pkraker** [comment]
My working hypothesis for explaining this problem was that the `ecodist::nmds` uses a different stress calculation than any other package and that this would lead to the different results. But as it turns out, ecodist has used the same stress calculation as `MASS::isoMDS` for quite some time now ([see documentation](https://cran.r-project.org/web/packages/ecodist/ecodist.pdf)). Therefore, the solution might be as simple as switching from `monoMDS` to `isoMDS` in `metaMDS`.
