### ISSUE TITLE
Loading information while list is still loading

### ISSUE THREAD

**Issue by tanteuschi** [OpenKnowledgeMaps/Headstart#80]
Users start clicking on visualization as soon as they see the bubbles appear. Problem: the vis is not ready until the list appears. Clicking at this point will not work. (could lead to frustration / worst case: leaving the website)
We need an indication that the vis is not ready yet. Loading cirlce..?

**Comment by Bubblbu** [comment]
Agree.

I still like the idea of a spinner instead of the viz, while it hasn't fully loaded. But in the meantime we could already preview the list. This would bridge the waiting times for the viz with something more productive than just waiting and drinking tea.

But we would need to solve certain problematic details, such as the viz <-> list interaction during that time.

**Comment by pkraker** [comment]
There is now a new version that reduces the loading time of the visualization (i.e. the calculation time of the force-directed layout) to under a second. This is shorter than the user's reaction time. I am therefore closing this issue.
